type: object
properties:
  test_cycles:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
          description: |
            環境名
        target_priorities:
          type: array
          items:
            type: string
            enum:
              - A
              - B
              - C
              - D
              - E
    required:
      - name
      - target_priorities
